# Use an official Node runtime as the parent image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle app source inside the Docker image
COPY . .

# Set the correct permissions for app.js
RUN chmod +x app.js

# Expose the port that the app listens on
EXPOSE 3000

# Start the app
CMD [ "node", "app.js" ]