version: '3.8'

services:
  database:
    container_name: express
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql-express:/var/lib/mysql

  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./node:/var/www/node
    depends_on:
      - database

volumes:
  mysql-express:
